export const users = [
    {
        "_id": "66890177859cca2a0c307ab2",
        "index": 0,
        "guid": "b2af7a0b-0a91-4707-86ac-60f225f280fc",
        "isActive": true,
        "balance": "$2,235.88",
        "picture": "http://placehold.it/32x32",
        "age": 22,
        "eyeColor": "blue",
        "name": "Wallace Hunter",
        "gender": "male",
        "company": "CYTREK",
        "email": "wallacehunter@cytrek.com",
        "phone": "+1 (989) 464-2831",
        "address": "153 Ditmars Street, Venice, New York, 8702",
        "about": "Ea duis proident est excepteur labore. Est commodo est duis esse deserunt sint aute. Lorem anim sit dolore esse et eu incididunt duis. Ullamco nisi mollit irure minim ea nulla sint voluptate exercitation mollit laboris. Deserunt consectetur pariatur excepteur dolore do deserunt occaecat non aute incididunt dolor eiusmod enim reprehenderit. Cillum anim non nisi pariatur.\r\n"
      },
      {
        "_id": "6689017728ca47da94a2f226",
        "index": 1,
        "guid": "01ad8838-ae38-4088-9bbb-72e60664278e",
        "isActive": false,
        "balance": "$1,812.58",
        "picture": "http://placehold.it/32x32",
        "age": 32,
        "eyeColor": "brown",
        "name": "Hewitt Parsons",
        "gender": "male",
        "company": "CYTREX",
        "email": "hewittparsons@cytrex.com",
        "phone": "+1 (942) 527-3013",
        "address": "802 Stuyvesant Avenue, Bath, Ohio, 4827",
        "about": "Ullamco cupidatat magna irure Lorem ullamco adipisicing Lorem elit consequat amet exercitation. Et pariatur laborum culpa do adipisicing adipisicing anim. Lorem et dolore nostrud irure sint sint irure proident aliquip nostrud fugiat cupidatat est ut.\r\n"
      },
      {
        "_id": "66890177bc9b288155c2c016",
        "index": 2,
        "guid": "eea68f21-c033-4dbf-b55f-3c8b0c106f45",
        "isActive": true,
        "balance": "$1,482.74",
        "picture": "http://placehold.it/32x32",
        "age": 23,
        "eyeColor": "blue",
        "name": "Diane Evans",
        "gender": "female",
        "company": "BIOHAB",
        "email": "dianeevans@biohab.com",
        "phone": "+1 (934) 576-2356",
        "address": "616 Barlow Drive, Spelter, Nevada, 9896",
        "about": "Ipsum elit incididunt aliqua non sunt dolore proident irure incididunt sunt ex in quis. Enim esse quis sint ut. Commodo id laboris anim deserunt cillum. Est laborum ut ad sunt sit eu culpa consectetur. Pariatur eu ad enim culpa cupidatat consequat. Amet laborum eu adipisicing sunt cillum officia fugiat ipsum.\r\n"
      },
      {
        "_id": "66890177b69b07cb08ed5fc4",
        "index": 3,
        "guid": "1692d3dc-2d31-468b-9394-82700fe912f4",
        "isActive": true,
        "balance": "$2,769.97",
        "picture": "http://placehold.it/32x32",
        "age": 21,
        "eyeColor": "brown",
        "name": "Leticia Moran",
        "gender": "female",
        "company": "TELEQUIET",
        "email": "leticiamoran@telequiet.com",
        "phone": "+1 (888) 543-3368",
        "address": "162 Fenimore Street, Kilbourne, Florida, 7865",
        "about": "Eiusmod incididunt nisi anim excepteur occaecat excepteur minim culpa reprehenderit culpa elit occaecat mollit. Laboris dolore minim veniam in officia consequat reprehenderit ipsum tempor qui ex minim. Ex sunt nostrud veniam esse. Laboris magna qui ea aliqua consequat fugiat sint aliqua. Veniam cupidatat reprehenderit quis officia. Sit nisi commodo anim reprehenderit anim consectetur in anim consequat dolor reprehenderit occaecat non commodo.\r\n"
      },
      {
        "_id": "66890177701ed0d2de5ebbf4",
        "index": 4,
        "guid": "48ec39f5-a8b3-404f-ac58-95fcd161b0d4",
        "isActive": true,
        "balance": "$3,201.39",
        "picture": "http://placehold.it/32x32",
        "age": 39,
        "eyeColor": "blue",
        "name": "Galloway Valentine",
        "gender": "male",
        "company": "KOZGENE",
        "email": "gallowayvalentine@kozgene.com",
        "phone": "+1 (879) 488-3213",
        "address": "488 Navy Walk, Logan, South Carolina, 2226",
        "about": "Nostrud adipisicing anim tempor est fugiat officia nostrud dolor duis aliquip veniam occaecat proident. Occaecat eiusmod nulla ea excepteur sit ea aliqua consectetur enim mollit incididunt nulla qui mollit. Sint qui sit fugiat ullamco id ex do dolore ipsum fugiat. Reprehenderit mollit elit voluptate et. Ipsum et ad nulla quis ut aliqua laboris.\r\n"
      },
      {
        "_id": "668901777e02fa4a68e97eba",
        "index": 5,
        "guid": "41774f73-b7a3-4e5e-9417-7ab3b375cdb0",
        "isActive": true,
        "balance": "$2,107.96",
        "picture": "http://placehold.it/32x32",
        "age": 40,
        "eyeColor": "green",
        "name": "Abbott Battle",
        "gender": "male",
        "company": "TROLLERY",
        "email": "abbottbattle@trollery.com",
        "phone": "+1 (965) 587-3103",
        "address": "510 Kaufman Place, Echo, Arkansas, 7466",
        "about": "Id irure ullamco nulla aute dolore adipisicing incididunt aliqua. Cillum nisi occaecat pariatur incididunt commodo sunt cillum dolor veniam incididunt exercitation nulla. Quis officia proident anim in dolor cillum occaecat eiusmod velit mollit officia. Tempor excepteur esse labore ullamco mollit amet cillum duis consequat tempor dolor labore ut. Mollit duis voluptate aliquip anim dolore fugiat id pariatur et dolor et.\r\n"
      },
      {
        "_id": "668901772a76832a6f3c750b",
        "index": 6,
        "guid": "48890edf-db8f-4274-86e8-da008a5509fa",
        "isActive": true,
        "balance": "$2,457.35",
        "picture": "http://placehold.it/32x32",
        "age": 20,
        "eyeColor": "brown",
        "name": "Acevedo Chase",
        "gender": "male",
        "company": "GEEKOL",
        "email": "acevedochase@geekol.com",
        "phone": "+1 (872) 457-2900",
        "address": "838 Maple Avenue, Tampico, Louisiana, 6999",
        "about": "Cillum et nostrud aliquip nisi. Sit qui tempor eiusmod anim laboris consectetur laborum eu. Cillum nostrud velit adipisicing in duis.\r\n"
      }
]